### PR TITLE
Added variable expansion as per style guide

### PR DESCRIPTION
**Pull request by theycallmemac**
I want to resolve issue #11 with a few of these commits as per the style guide

### CODE REVIEW

**Comment by vaage** [comment]
Hey @theycallmemac Thanks for taking this on. Could you make all changes to the shell script to be in one pull request so that we have one pull request that will close the bug?

**Comment by theycallmemac** [comment]
No problem. Honestly I'm not even near my terminal now, I thought I did this right the first time sorry. How will I fix it when I get back, just so I can know what to do.

**Comment by vaage** [comment]
I am going to assume that you know git well, if anything I say does not make sense, let me know and I can dig into it more. All the branches you pushed, merge them into one branch and they push that branch.

**Comment by theycallmemac** [comment]
It has been done, it will close all requests bar the one which has been pushed to resolve issue #11

**Pull request closed without merging**
